### ISSUE TITLE
Error message after installation

### ISSUE THREAD

**Issue by tischi** [clij/clij2#48]
```
(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_202 [64-bit]; Mac OS X 10.14.6; 277MB of 8916MB (3%)
 
java.lang.NoClassDefFoundError: net/haesleinhuepf/clij/macro/CLIJMacroPlugin
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at ij.macro.Functions.call(Functions.java:4519)
	at ij.macro.Functions.getStringFunction(Functions.java:276)
	at ij.macro.Interpreter.getStringTerm(Interpreter.java:1475)
	at ij.macro.Interpreter.getString(Interpreter.java:1453)
	at ij.macro.Interpreter.doStatement(Interpreter.java:333)
	at ij.macro.Interpreter.doStatements(Interpreter.java:264)
```

After enabling the clij2 update site.

**Comment by haesleinhuepf** [comment]
Hi Christian @tischi ,

can you please check if the update sites "clij" and "clij2" are both activated as described in the [installation instructions](https://clij.github.io/clij2-docs/installationInFiji)?

Let me know if this helps!

Best,
Robert

**Comment by tischi** [comment]
Yes, figured this out myself meanwhile, adding `clij` fixes it.

**Comment by haesleinhuepf** [comment]
Thanks! Have a great weekend!
