### ISSUE TITLE
Can't run ClijX richradson lucy deconvolution using clfft

### ISSUE THREAD

**Issue by Hark64** [clij/clij2#66]
When I try to run Clijx richardson lucy deconvolution, I get this exception. I am running Fiji in linux and the server I am on has two nvidia gpus and a cpu so I think this may be an issue of it trying to create a context for each of these three devices? Although I am not sure since I'm having trouble analyzing this error.
`(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Linux 3.10.0-1160.83.1.el7.x86_64; 913MB of 121978MB (<1%)
 
net.haesleinhuepf.clij.clearcl.exceptions.ClearCLTooManyContextsException: Too many contexts have been created and not released
	at net.haesleinhuepf.clij.clearcl.ClearCLDevice.createContext(ClearCLDevice.java:221)
	at net.haesleinhuepf.clij.CLIJ.<init>(CLIJ.java:156)
	at net.haesleinhuepf.clij.CLIJ.getInstance(CLIJ.java:172)
	at net.haesleinhuepf.clij.CLIJ.getInstance(CLIJ.java:166)
	at net.haesleinhuepf.clij.macro.AbstractCLIJPlugin.run(AbstractCLIJPlugin.java:265)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:266)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:246)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
`

**Comment by haesleinhuepf** [comment]
Hi @Hark64 ,

I've seen similar errors before. They are typically related to some software/driver installation. Would you mind trying the solutions discussed in these image.sc threads?

* https://forum.image.sc/search?q=Too%20many%20contexts%20have%20been%20created%20and%20not%20released

let us know if this helps!

best,
Robert
